name: shhider
title: shhider的个人博客
description: 前端开发一枚，目前就职于网易杭州。
email: shhider@163.com
url: http://shhider.github.io
baseurl: /

encoding: utf-8

permalink: /blog/:year/:month/:title
paginate: 12
paginate_path: "articles/page:num"

markdown: kramdown
kramdown:
    input: GFM                # use Github Flavored Markdown !important
